feat: AntiClock,AntiPistonを実装
jaoafa/ChuoCity pull request #43
Opened 2022-03-03 14:29 UTC by yuuahp

(ついでにMainのプラグイン登録処理も整理)

2022-03-03 20:06 UTC, book000 requested changes

2022-03-03 20:06 UTC, book000 commented on src/main/java/com/jaoafa/ChuoCity/Event/Event_AntiClockRedstone.java
> +    private record RSData(Long ms, Integer times) {
```suggestion
    private record RSData(long ms, int times) {
```
NULL許容する必要あるかなあ？

2022-03-03 20:06 UTC, book000 commented on src/main/java/com/jaoafa/ChuoCity/Event/Event_AntiClockRedstone.java
> +        var text = Component.text().append(
```suggestion
        Component text = Component.text().append(
```
型推論いるぅ…？いいけど…

2022-03-03 20:06 UTC, book000 commented on src/main/java/com/jaoafa/ChuoCity/Main.java
> +        }}.forEach(listener -> getServer().getPluginManager().registerEvents(listener, this));
```suggestion
        List.of(
            new Event_ChuoCityRailChecker(),
            new Event_AntiBlockUnderDestroy(),
            new Event_ChuoCityY50Destroy(),
            new Event_AntiClockRedstone(),
            new Event_AntiClockPiston(),
            new Event_PlaceTNT(),
            new Event_AntiCreatureSpawn(),
            new Event_AntiDiffusionWaterLava(),
            new Event_AntiInteract(),
            new Event_AntiTooManyArmorStand(),
            new Event_RegionCommand(),
            new Event_Bamboo(),
            new Event_Beehive()
        ).forEach(listener -> getServer().getPluginManager().registerEvents(listener, this));
```

2022-03-04 02:38 UTC, yuuahp commented on src/main/java/com/jaoafa/ChuoCity/Event/Event_AntiClockRedstone.java
> +        var text = Component.text().append(
変えるのを忘れるなどしていた...

2022-03-04 11:48 UTC, book000 approved these changes

2022-03-04 11:48 UTC, merged